### ISSUE TITLE
MongoDB example

### ISSUE THREAD

**Issue by mikekelly** [braintree/curator_rails_example#2]
I've looked through the specs in curator but I'm still not 100% on the correct way to switch to the mongo datastore. Please could you guys create a branch demonstrating how best to do this?

I've got a little of the way through but hit an issue passing in domain models that include active model validations, I get this error:

`BSON::InvalidDocument (Cannot serialize ActiveModel::Errors as a BSON type; it either isn't supported or won't translate to BSON.)`

**Comment by pgr0ss** [comment]
I think you just need to add `config/mongo.yml` and then create an initializer with something like:

``` ruby
Curator.configure(:mongo) do |config|
  config.environment = Rails.env
  config.database = "your_app_name"
  config.mongo_config_file = File.expand_path(File.dirname(__FILE__) + "/../config/mongo.yml")
end
```

I'll try to get a branch going, though.
